version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'ci'
      - 'dependencies'
    commit-message:
      prefix: 'ci(dependencies)'
    assignees:
      - 'gregoranders'
    target-branch: 'development'

  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'build(dependencies)'
    assignees:
      - 'gregoranders'
    target-branch: 'development'
