---
engines:
  coverage:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: false
  markdownlint:
    enabled: false
  metric:
    enabled: true
  remark-lint:
    enabled: false
  stylelint:
    enabled: false
  tslint:
    enabled: false
exclude_paths:
  - '.github/**'
  - '.vscode/**'
  - 'src/test/**'
  - 'docs/**'
  - '*.md'
  - 'config/commitlint.config.js'
  - 'config/conventionalcommit.json'
