---
engines:
  coverage:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
  markdownlint:
    enabled: true
  metric:
    enabled: true
  remark-lint:
    enabled: true
  stylelint:
    enabled: true
  tslint:
    enabled: false
exclude_paths:
  - '.github/**'
  - '.vscode/**'
  - 'src/test/**'
  - 'docs/**'
  - 'CHANGELOG.md'
  - 'config/commitlint.config.js'
  - 'config/commitlint.config.js'
