name: Main CI
on:
  push:
    branches:
      - main
env:
  CI: true
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GITHUB_BRANCH: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_COMMIT: ${{ github.sha }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ '17' ]
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'corretto'
          cache: 'gradle'
          java-version: ${{ matrix.java }}
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Echo JAVA version
        run: java --version
      - name: Cache SonarCloud packages
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v3.2.6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Echo Gradle version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --version
      - name: Execute clean, check and build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --stacktrace --scan clean check build
      - name: Sonarcube analyze
        if: matrix.os == 'ubuntu-latest'
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: --info --stacktrace sonarqube
      - name: Upload reports as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports-jdk${{ matrix.java }}-${{ matrix.os }}
          path: build/reports
          retention-days: 2
      - name: Upload test results as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-results-jdk${{ matrix.java }}-${{ matrix.os }}
          path: build/test-results
          retention-days: 1
      - name: Prepare spock reports artifact
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p build/gh-pages
          cp build/reports/spock/* build/gh-pages
          cp docs/gh-pages/* build/gh-pages
      - name: Upload spock reports as an artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: build/gh-pages
          retention-days: 1

  publish-spock-reports:
    runs-on: ubuntu-latest
    name: Publish Spock Reports
    needs: build
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: gh-pages
          path: gh-pages-artifact
      - name: Get cached gems
        uses: actions/cache@v3.2.6
        with:
          path: gh-pages-artifact
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Copy docs
        run: |
          sudo apt update
          sudo apt install bundler
          cd gh-pages-artifact
          bundle update
          bundle exec github-pages build
          touch _site/.nojekyll
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-artifact/_site
          enable_jekyll: false

  publish-test-results:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ '17' ]
      fail-fast: false
    name: Publish Unit Tests Results ${{ matrix.os }} JDK ${{ matrix.java }}
    needs: build
    if: always()
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: junit-results-jdk${{ matrix.java }}-${{ matrix.os }}
          path: junit-artifact
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          check_name: Unit Test Results jdk${{ matrix.java }}-${{ matrix.os }}
          junit_files: junit-artifact/**/*.xml

  release:
    name: Release ${{ matrix.os }} JDK ${{ matrix.java }} NodeJS ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ '17' ]
        node-version: [18.x]
      fail-fast: false
    needs: build
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
