name: Release CI
on:
  push:
    tags:
      - 'v*'
env:
  CI: true
  GITHUB_BRANCH: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_COMMIT: ${{ github.sha }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ '17' ]
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'corretto'
          cache: 'gradle'
          java-version: ${{ matrix.java }}
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Echo JAVA version
        run: java --version
      - name: Cache SonarCloud packages
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v3.2.1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Echo Gradle version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --version
      - name: Execute clean, check and build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --stacktrace --scan clean check build
      - name: Sonarcube analyze
        if: matrix.os == 'ubuntu-latest'
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: --info --stacktrace sonarqube
      - name: Publish package
        if: matrix.os == 'ubuntu-latest'
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          arguments: --info --stacktrace publish
